services:
  db:
    image: postgres
    container_name: refx
    restart: always
    environment:
      POSTGRES_USER: refx_user
      POSTGRES_PASSWORD: refx-password
      POSTGRES_DB: refx_db
    ports:
      - "5432:5432"
  redis:
    image: redis
    restart: always
    container_name: refx-redis
    ports:
      - "6379:6379"
